name: Publish VSCode Extension Switcher

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2

      - run: bun install

      - run: bun run compile
        working-directory: ./packages/vscode-ext-switcher

      - run: xvfb-run -a bun run test
        working-directory: ./packages/vscode-ext-switcher

      - run: bun run build
        working-directory: ./packages/vscode-ext-switcher

      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: ./packages/vscode-ext-switcher

      - uses: softprops/action-gh-release@v1
        with:
          tag_name: vscode-ext-switcher-${{ steps.package-version.outputs.current-version}}
          files: |
            ./packages/vscode-ext-switcher/vscode-ext-switcher-*.vsix
